version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_network
    volumes:
      - media:/data/media/
      - static:/data/static/
      - /home/loooooky1234/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_test_image:3
    networks:
      - gis_2ban_network
    volumes:
      - media:/home/gis_project/media/
      - static:/home/gis_project/staticfiles/

networks:
  gis_2ban_network:

volumes:
  media:
  static: